server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.22.204.134:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: item
          uri: lb://item-service
          predicates:
            - Path=/items/**
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: pay
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: trade
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**, /addresses/**
        - id: search
          uri: lb://search-service
          predicates:
            - Path=/search/**
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi